### ISSUE TITLE
Rename "admin" menu to something relevant

### ISSUE THREAD

**Issue by danchopon** [ernisov/study-dorm#20]
<img width="1220" alt="Screen Shot 2019-06-04 at 4 05 34 PM" src="https://user-images.githubusercontent.com/18620037/58870871-cd809e00-86e2-11e9-9c2f-902b07d99113.png">

**Comment by ernisov** [comment]
Renamed to Users
![image](https://user-images.githubusercontent.com/10906013/58907548-422df980-8730-11e9-9d6f-aa452d3eb318.png)
