### ISSUE TITLE
Rename Logo to "KSTU Dormitory"

### ISSUE THREAD

**Issue by danchopon** [ernisov/study-dorm#21]
<img width="1220" alt="Screen Shot 2019-06-04 at 4 05 34 PM" src="https://user-images.githubusercontent.com/18620037/58871070-2a7c5400-86e3-11e9-8d9d-1fe96c390409.png">

**Comment by ernisov** [comment]
done
![image](https://user-images.githubusercontent.com/10906013/58907761-b8caf700-8730-11e9-972c-2f16d3642903.png)
