### ISSUE TITLE
Жесткий баг

### ISSUE THREAD

**Issue by Loctor-agar** [ernisov/study-dorm#34]
При авторизации пользователя Student 
и нажатии на кнопку назад выходит такой баг!!
![image](https://user-images.githubusercontent.com/29569047/59156979-7fdea980-8ac5-11e9-9480-aafcad6d6016.png)
![image](https://user-images.githubusercontent.com/29569047/59157002-b74d5600-8ac5-11e9-8c42-04063875b690.png)

**Comment by ernisov** [comment]
done
